# Generated by Django 4.2.2 on 2024-05-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='person',
        ),
    ]
