# Generated by Django 4.2.2 on 2023-09-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_person_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
