# Generated by Django 4.2.2 on 2024-05-03 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_geofencing_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_sub_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.subunit'),
        ),
    ]
