# Generated by Django 4.2.2 on 2024-05-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_geofencing_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofencing',
            name='coordinates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
