# Generated by Django 4.2.2 on 2024-05-20 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_geofencing_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofencing',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PathTrace',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('path_line', models.TextField(blank=True, null=True)),
                ('persons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
            bases=('app.basemodel',),
        ),
    ]
