# Generated by Django 4.2.2 on 2024-05-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_geofencing_coordinates_pathtrace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathtrace',
            name='path_line',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
