# Generated by Django 4.2.2 on 2024-06-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_pathtrace_path_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathtrace',
            name='path_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
