# Generated by Django 4.2.2 on 2024-07-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_deployedunits_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedunits',
            name='deployement_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
