# Generated by Django 4.2.2 on 2024-07-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_deployedunits_deployement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedunits',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deployedunits',
            name='lng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
