# Generated by Django 4.2.2 on 2024-07-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_deployedunits_lat_deployedunits_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployedunits',
            old_name='lat',
            new_name='coordinates',
        ),
        migrations.RemoveField(
            model_name='deployedunits',
            name='lng',
        ),
    ]
