# Generated by Django 4.2.2 on 2024-07-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_lat_deployedunits_coordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployedunits',
            name='persons',
        ),
        migrations.AddField(
            model_name='deployedunits',
            name='personels_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
