# Generated by Django 4.2.2 on 2024-07-17 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_deployement_name_deployedunits_deployment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployedunits',
            name='personels_id',
        ),
        migrations.AddField(
            model_name='deployedunits',
            name='persons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.person'),
        ),
    ]
