# Generated by Django 4.2.2 on 2024-07-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_deployedunits_personels_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployedunits',
            name='persons',
        ),
        migrations.AddField(
            model_name='deployedunits',
            name='persons',
            field=models.ManyToManyField(to='app.person'),
        ),
    ]
