# Generated by Django 4.2.2 on 2024-07-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_deployedunits_persons_deployedunits_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedunits',
            name='is_arrived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
