# Generated by Django 4.2.2 on 2024-07-30 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_deployedunits_is_arrived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployedunits',
            name='is_arrived',
        ),
        migrations.RemoveField(
            model_name='deployedunits',
            name='persons',
        ),
        migrations.CreateModel(
            name='DeployedUnitPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_arrived', models.BooleanField(blank=True, default=False, null=True)),
                ('deployed_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.deployedunits')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
    ]
