# Generated by Django 4.2.2 on 2024-07-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_deployedunits_is_arrived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedunits',
            name='persons',
            field=models.ManyToManyField(through='app.DeployedUnitPerson', to='app.person'),
        ),
    ]
