# Generated by Django 4.2.2 on 2024-07-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_deployedunits_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedunits',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
