# Generated by Django 4.2.2 on 2024-07-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_deployedunits_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
